
// this file was generated by create_new_folder_project.js

package polymorphism_lesson

import kotlin_helpers.*


fun f_print_variable(variable: String){
    println("'f_print_variable(variable: String)' was called")
    println("variable is $variable")
}

fun f_print_variable(variable: Int){
    println("'f_print_variable(variable: Int)' was called")
    println("variable is $variable")
}

fun main() {

    f_print_variable("this is a string"); 

    f_print_variable(11235);

    println("main function  was executed")
}
