
// this file was generated by create_new_folder_project.js

import kotlin_helpers.*

fun main() {

    // basic types 
    var asdf = 3

    kotlin_helpers.cd printf(asdf)

    println("main function  was executed")
}
