
// this file was generated by create_new_folder_project.js

package kotlin_helpers

fun printf(test: Int){ 
    
    println("test");
    
    println(test);

}

//class asdf { /*...*/ }

fun main() {
    println("main function  was executed")

    printf(10);

}
