var arguments = process.argv

var node_binary = arguments.shift()
var script_path_filename = arguments.shift()

const { exec } = require("child_process");

var path = require('path');
var current_node_script_name = path.basename(__filename);

if(arguments.length == 0){
    console.warn('no foldername specified, do it with:')
    console.info(`${node_binary.split('/').pop()} ${script_path_filename.split('/').pop()} the_folder_name_here`)
    process.exit(1)
}

var folder_name = arguments.shift()

var fs = require('fs');
var dir = './'+folder_name;

if (!fs.existsSync(dir)){
    
    fs.mkdirSync(dir);
   
}else{
    //console.log(`directory : ${folder_name} already exists`)
}

var generated_by_nodefile_header = `this file was generated by ${current_node_script_name}`; 
 
var kotlin_helpers_name = 'kotlin_helpers'

var compile_and_run_file_content = `
# ${generated_by_nodefile_header}

# compile
## compile ${kotlin_helpers_name} , a small helper package/library
kotlinc ./../${kotlin_helpers_name}/${kotlin_helpers_name}.kt -d ./../${kotlin_helpers_name}/${kotlin_helpers_name}.jar

## compile the main file with the dependencies
kotlinc ${folder_name}.kt -classpath ./../${kotlin_helpers_name}/${kotlin_helpers_name}.jar -include-runtime -d ${folder_name}.jar

./run.sh

`

var kotlin_file_filename = folder_name+".kt"


var main_class_package_name = folder_name; 

// kotlin behaviour 
//  main_file.kt (with a line 'package_name') 
//  becomes 
// package_name.Main_fileKt

var kotlin_file_filename_parts = kotlin_file_filename.split(".");
var kotlin_file_filename_without_extension = kotlin_file_filename_parts[0];
var kotlin_file_filename_extension = kotlin_file_filename_parts.pop();

var first_letter_to_uppercase = function(string){
    return string.charAt(0).toUpperCase() + string.slice(1);
}

var java_binary_weird_main_class_name_prefix = main_class_package_name

var java_binary_weird_main_class_name_suffix = `${first_letter_to_uppercase(kotlin_file_filename_without_extension)}${first_letter_to_uppercase(kotlin_file_filename_extension)}` 

var java_binary_weird_main_class_name = `${java_binary_weird_main_class_name_prefix}.${java_binary_weird_main_class_name_suffix}`


var run_file_content = `
# ${generated_by_nodefile_header}

# run 

java -classpath ${folder_name}.jar:./../${kotlin_helpers_name}/${kotlin_helpers_name}.jar ${java_binary_weird_main_class_name}
`

var run_file_name = `run.sh`

var kotlin_file_content = `
// this file was generated by ${current_node_script_name}

package ${main_class_package_name}

import ${kotlin_helpers_name}.*

fun main() {
    println("main function  was executed")
}
`



var compile_and_run_file_name = "compile_and_run.sh"

if (!fs.existsSync(folder_name+'/'+compile_and_run_file_name)){

    fs.writeFile(folder_name+'/'+compile_and_run_file_name, compile_and_run_file_content, function(err) {
        if(err) {
            return console.log(err);
        }
        console.log("The "+folder_name+'/'+compile_and_run_file_name+" file was saved!");
        
        // fs.chmod( 
        //     folder_name+'/'+compile_and_run_file_name, 
        //     //"+x" //not working
        //     777 ,
        //     function(){
        //         console.log("The "+folder_name+'/'+compile_and_run_file_name+" file was made executable (chmod +x)!");
        //     } )
        exec_return = exec("chmod +x "+folder_name+'/'+compile_and_run_file_name, function(err, stdout, stderr) {
            if (err) {
              // should have err.code here?  
            }
            console.log(stdout);
          });
          

    });


}
if (!fs.existsSync(folder_name+'/'+run_file_name)){

    fs.writeFile(folder_name+'/'+run_file_name, run_file_content, function(err) {
        if(err) {
            return console.log(err);
        }
        console.log("The "+folder_name+'/'+run_file_name+" file was saved!");
        
        // fs.chmod( 
        //     folder_name+'/'+run_file_name, 
        //     //"+x" //not working
        //     777 ,
        //     function(){
        //         console.log("The "+folder_name+'/'+run_file_name+" file was made executable (chmod +x)!");
        //     } )
        exec_return = exec("chmod +x "+folder_name+'/'+run_file_name, function(err, stdout, stderr) {
            if (err) {
              // should have err.code here? 
                console.log("asdfasdf asdfa asdf asdfKK");
                console.log(err);
                console.log(folder_name);

            }
            console.log("asdf asdf asdf adfs fads");
          });
          

    });


}

if (!fs.existsSync(folder_name+'/'+kotlin_file_filename)){

    fs.writeFile(folder_name+'/'+kotlin_file_filename, kotlin_file_content, function(err) {
        if(err) {
            return console.log(err);
        }
        console.log("The "+folder_name+'/'+kotlin_file_filename+" file was saved!");
    }); 

}

console.log('done')