
# this file was generated by create_new_folder_project.js

# compile
## compile kotlin_helpers , a small helper package/library
kotlinc ./../kotlin_helpers/kotlin_helpers.kt -d ./../kotlin_helpers/kotlin_helpers.jar

## compile the main file with the dependencies
kotlinc game_2048_tornadofx.kt -classpath ./../kotlin_helpers/kotlin_helpers.jar;./javafx.base.jar;./javafx.controls.jar;./javafx.fxml.jar;./javafx.graphics.jar;./javafx.media.jar;./javafx.swing.jar;./javafx-swt.jar;./javafx.web.jar-include-runtime -d game_2048_tornadofx.jar

./run.sh
