
// this file was generated by create_new_folder_project.js

package game_2048_tornadofx

import javafx.geometry.Pos
import javafx.stage.Stage
import tornadofx.*

import kotlin_helpers.*

fun main() {
    println("main function  was executed")
}
