
// this file was generated by create_new_folder_project.js

package val_and_var

import kotlin_helpers.*

fun main() {

    val s_val_name = "hans" 
    dnd(s_val_name)

    //      s_val_name = "tobi"
    //      dnd(s_val_name)
    // error: val cannot be reassigned

    var s_var_name = "hans" 
    dnd(s_var_name)
    

    println("main function  was executed")
}
