cd
// this file was generated by create_new_folder_project.js

package inheritance_lesson

import kotlin_helpers.*

fun main() {
    println("main function  was executed")
}



class Animal(
    s_name: String
){
    val s_name = s_name;

    fun make_private_noise(){
        println("private noise ")
    }
    
}