
// this file was generated by create_new_folder_project.js

package game2048_console

import kotlin_helpers.*

fun main() {

    println("main function  was executed")
    
    val point_2_d = Point_2_d(2,2)
    
    //dnd dump not die from kotlin_helpers
    dnd(point_2_d)

}

class Point_2_d(
    x: Int, 
    y: Int) {
    val x = x
    val y = y 
}

