
// this file was generated by create_new_folder_project.js

package strings_lesson

import kotlin_helpers.*

fun main() {


    val n_a = 2; 
    println("n_a is $n_a")

    // $varname for variable in string literal
    val n_b = 3; 
    println("n_b is $n_a")

    // ${} for expressions in string literal
    println("n_a * n_b is ${n_a * n_b}")


    println("expression in stringliteral : ${i_give_ten() * n_a * n_b}")
    
    val evald_expression_as_var = i_give_ten() * n_a * n_b 
    println("var in stringliteral : $evald_expression_as_var")


    println("main function  was executed")
}


fun i_give_ten(): Int{
    return 10
}
