
// this file was generated by create_new_folder_project.js

package kotlin_helpers_test

import kotlin_helpers.*

fun main() {

    dnd("arrayOf")

    var a_nums = arrayOf(1,1,2,3,5)
    
    dnd(a_nums)

    dnd("ArrayList")

    var a_nums_arraylist = ArrayList<Int>()
    a_nums_arraylist.add(1)
    a_nums_arraylist.add(1)
    a_nums_arraylist.add(2)
    a_nums_arraylist.add(3)
    a_nums_arraylist.add(5)

    dnd(a_nums_arraylist)

    dnd("MutableList")

    var a_nums_mutablelist = MutableList<Int>(0){0}
    a_nums_mutablelist.add(1)
    a_nums_mutablelist.add(1)
    a_nums_mutablelist.add(2)
    a_nums_mutablelist.add(3)
    a_nums_mutablelist.add(5)
    
    dnd(a_nums_mutablelist)


    val o_simple_object = Simple_object(11235)
    
    dnd(o_simple_object)
    // for(prop in o_simple_object::class.members){
    //     println(prop)
    // }
    println(o_simple_object::class.members)

    println("main function  was executed")
}

class Simple_object(
    n_number: Int
){
    val n_number = n_number
}

