
// this file was generated by create_new_folder_project.js


package asynchronous_programming

import java.io.BufferedReader
import java.io.InputStreamReader
import java.net.URL


import kotlin_helpers.*

fun f_test(){
    println("safd");
}

fun main() {

    val o_thread = Thread();
    o_thread.start();

    // val o_thread = Thread(f_test);
    
    println("main function  was executed")
}

// //  synchronous = gleichzeitig aber beim programmieren nicht -.- wtf welcher verdammter huhrensohn hat sich das ueberlegt

// // asynchronous = 

// fun f_s_url_request_serial_aka_synchornous(): Boolean{

// return false;

// }

// fun f_s_url_request(
//     s_url : String
// ): String{

    
//     val o_connection = s_url.openConnection()
//     BufferedReader(
//         InputStreamReader(
//             o_connection.getInputStream()
//         )
//     ).use({
//         o_input -> 
//         var s_line: String?
//         while(
//             s_input.readline().also{
//                 s_line = it
//             } != null
//         ){
//             println("s_line")
//             println(s_line)
//         }
//     })
    


// }