
// this file was generated by create_new_folder_project.js

package callbacks_lesson

import kotlin_helpers.*
import kotlin.jvm.internal.Lambda

fun main() {
    
    var a_arr = mutableListOf(1,2,3,4);

    // anonymous function / anonymous lambda / 
    custom_foreach(a_arr, { n_val: Int -> println("int is : $n_val")})
    
    
    val f_print_n_times_two = { n_value : Int -> println("int * 2 is ${n_value*2}")}

    custom_foreach(a_arr, f_print_n_times_two)
}


// fun custom_foreach(a_arr: MutableList, f_function: Function){ //datatype function not working
fun custom_foreach(a_arr: MutableList<Int>, f_function: (n_array_value: Int) -> Unit){

    for(n_array_value in a_arr){
        f_function(n_array_value)
    }
}