
// this file was generated by create_new_folder_project.js

package thread_lesson

import kotlin_helpers.*

fun main() {
    val o_thread = Thread(); 
    o_thread.start()


    val o_thread_with_runnable_lambda = Thread(
        Runnable{
            Thread.sleep(1000)
            println("Thread is done")
        }
    )
    o_thread_with_runnable_lambda.start()
    println("done")
}
