
// this file was generated by create_new_folder_project.js
package package_a

fun function_from_package_a(){
    println(" hurray function_from_package_a was called ! ")
}

// fun main(){
    
// }
// class Main { /*...*/ }

// fun main() {
//     println("main function  was executed")
// }
