
// this file was generated by create_new_folder_project.js

package extensions_lesson

import kotlin_helpers.*

fun main() {


    println("main function  was executed")

    // we can extend like this 

    fun String.every_second_letter_to_upper(): String {
        
        var s_new = ""
        

        for(n_index in 0..this.length-1){
            var s = this[n_index].toChar()
                        
            if(n_index % 2 == 0){
                s_new += s.uppercaseChar().toString()
            }else{
                s_new += s.toString()
            }
            
        }
        return s_new

        // return s_new; 
    
    }

    fun String.to_nonsense() : String {
        return "nonsense"
    }

    println("asdf".to_nonsense())
    println("hello my name is mud".every_second_letter_to_upper())


    
}
